import { option, personalTemplateBase, type SetupSection } from "./types";

const lifeStateOptions = [
  option("MOSTLY_STABLE", "Mostly Stable", { bar_level: 0.35, accent: "primary" }),
  option("OVERWHELMING", "Overwhelming", { bar_level: 0.85, accent: "error" }),
  option("VERY_BUSY", "Very Busy", { bar_level: 0.7, accent: "tertiary" }),
  option("UNPREDICTABLE", "Unpredictable", { bar_level: 0.55, accent: "tertiary" }),
  option("TRYING_TO_RESET", "Trying to Reset", { bar_level: 0.45, accent: "primary" }),
  option("BUILDING_MOMENTUM", "Building Momentum", { bar_level: 0.65, accent: "primary" }),
];

const lifeOpsSections: SetupSection[] = [
  {
    section_id: "operating_mode",
    title: "Select Operating Mode",
    subtitle: "System State",
    type: "card_grid",
    field_key: "current_life_state",
    options: lifeStateOptions,
    required: true,
  },
  {
    section_id: "desired_direction",
    title: "Desired Direction",
    type: "chips",
    field_key: "desired_directions",
    options: [
      option("CALMNESS", "Calmness"),
      option("STRUCTURE", "Structure"),
      option("ENERGY", "Energy"),
      option("RECOVERY", "Recovery"),
      option("FOCUS", "Focus"),
      option("STABILITY", "Stability"),
      option("FLEXIBILITY", "Flexibility"),
      option("MOMENTUM", "Momentum"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "pressure_sources",
    title: "What creates pressure?",
    type: "chips",
    field_key: "pressure_sources",
    options: [
      option("COMMITMENTS", "Commitments"),
      option("MONEY", "Money"),
      option("NO_ROUTINE", "No Routine"),
      option("BURNOUT", "Burnout"),
      option("OVERLOAD", "Overload"),
      option("TASKS", "Tasks"),
      option("NO_RECOVERY", "No Recovery"),
      option("CHANGE", "Change"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "recovery_supports",
    title: "What restores you?",
    type: "chips",
    field_key: "recovery_supports",
    options: [
      option("QUIET_TIME", "Quiet Time"),
      option("WALKS", "Walks"),
      option("SLEEP", "Sleep"),
      option("REFLECTION", "Reflection"),
      option("EXERCISE", "Exercise"),
      option("PEOPLE", "People"),
      option("FLEXIBILITY", "Flexibility"),
      option("FINANCIAL_CLARITY", "Financial Clarity"),
    ],
    required: true,
    min_selected: 1,
  },
];

export const lifeOperationsTemplate = personalTemplateBase(
  "life_operations",
  "LIFE_OPERATIONS",
  "Life Operations Setup",
  "Initializing your personal neural operating system. Let's align your rhythm.",
  {
    badge_label: "LIFE OPERATIONS",
    title: "Life Operations Setup",
    body: "Initializing your personal neural operating system. Let's align your rhythm.",
  },
  lifeOpsSections,
  {
    label: "Begin My New Rhythm",
    footer_note: "Your rhythm adapts as you live",
  },
  {
    title: "Structure Seeker",
    badge_label: "Intelligence Profile",
  },
);

const futureBuildingSections: SetupSection[] = [
  {
    section_id: "building_focus",
    title: "What are you building?",
    type: "single_choice",
    field_key: "building_focus",
    options: [
      option("CAREER_GROWTH", "Career Growth"),
      option("BUSINESS_GROWTH", "Business Growth"),
      option("FINANCIAL_FREEDOM", "Financial Freedom"),
      option("LEARNING_SKILLS", "Learning & Skills"),
      option("CREATIVE_PROJECT", "Creative Project"),
      option("PERSONAL_REINVENTION", "Personal Reinvention"),
    ],
    required: true,
  },
  {
    section_id: "current_state",
    title: "Where are you today?",
    type: "single_choice",
    field_key: "current_state",
    options: [
      option("JUST_STARTING", "Just Starting"),
      option("EXPLORING_OPTIONS", "Exploring Options"),
      option("MAKING_PROGRESS", "Making Progress"),
      option("BUILDING_MOMENTUM", "Building Momentum"),
    ],
    required: true,
  },
  {
    section_id: "values",
    title: "What matters most?",
    type: "chips",
    field_key: "values",
    options: [
      option("GROWTH", "Growth"),
      option("FREEDOM", "Freedom"),
      option("IMPACT", "Impact"),
      option("SECURITY", "Security"),
      option("PURPOSE", "Purpose"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "friction_sources",
    title: "What slows you down?",
    type: "chips",
    field_key: "friction_sources",
    options: [
      option("LACK_OF_TIME", "Lack Of Time"),
      option("LACK_OF_CLARITY", "Lack Of Clarity"),
      option("DISTRACTIONS", "Distractions"),
      option("BURNOUT", "Burnout"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "momentum_drivers",
    title: "What accelerates progress?",
    type: "chips",
    field_key: "momentum_drivers",
    options: [
      option("DAILY_PROGRESS", "Daily Progress"),
      option("LEARNING", "Learning"),
      option("FOCUS_TIME", "Focus Time"),
      option("ROUTINE", "Routine"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "future_feeling",
    title: "How does the future feel?",
    type: "single_choice",
    field_key: "future_feeling",
    options: [
      option("EXCITING", "Exciting"),
      option("HOPEFUL", "Hopeful"),
      option("CONFIDENT", "Confident"),
      option("UNCLEAR", "Unclear"),
      option("STUCK", "Stuck"),
      option("OVERWHELMING", "Overwhelming"),
    ],
    required: true,
  },
];

export const futureBuildingTemplate = personalTemplateBase(
  "future_building",
  "FUTURE_BUILDING",
  "Future Building Setup",
  "Configure the direction you want your future to move.",
  {
    badge_label: "FUTURE BUILDING",
    title: "Future Building Setup",
    body: "Configure the direction you want your future to move.",
  },
  futureBuildingSections,
  {
    label: "Activate Future Building",
    footer_note: "Your future system adapts as you build",
  },
  {
    title: "Future Builder",
    badge_label: "Intelligence Profile",
  },
);

const lifestyleSections: SetupSection[] = [
  {
    section_id: "moment_name",
    title: "Name this moment",
    subtitle: "Give your lifestyle journey a name.",
    type: "text",
    field_key: "moment_name",
    options: [],
    required: true,
  },
  {
    section_id: "lifestyle_vision",
    title: "Lifestyle vision",
    type: "single_choice",
    field_key: "lifestyle_vision",
    options: [
      option("BALANCED", "Balanced"),
      option("ADVENTUROUS", "Adventurous"),
      option("MINIMAL", "Minimal"),
      option("SOCIAL", "Social"),
      option("CREATIVE", "Creative"),
      option("WELLNESS_FOCUSED", "Wellness Focused"),
    ],
    required: true,
  },
  {
    section_id: "current_lifestyle",
    title: "Current lifestyle",
    type: "single_choice",
    field_key: "current_lifestyle",
    options: [
      option("THRIVING", "Thriving"),
      option("STEADY", "Steady"),
      option("STRETCHED", "Stretched"),
      option("RECOVERING", "Recovering"),
      option("REINVENTING", "Reinventing"),
    ],
    required: true,
  },
  {
    section_id: "health_energy",
    title: "Health & energy",
    type: "single_choice",
    field_key: "health_energy",
    options: [
      option("LOW", "Low"),
      option("STEADY", "Steady"),
      option("HIGH", "High"),
      option("VARIABLE", "Variable"),
    ],
    required: true,
  },
  {
    section_id: "daily_habits",
    title: "Daily habits",
    type: "chips",
    field_key: "daily_habits",
    options: [
      option("MORNING_ROUTINE", "Morning Routine"),
      option("MOVEMENT", "Movement"),
      option("MINDFULNESS", "Mindfulness"),
      option("SLEEP", "Sleep"),
      option("MEAL_PREP", "Meal Prep"),
    ],
    required: false,
  },
  {
    section_id: "work_life_balance",
    title: "Work-life balance",
    type: "chips",
    field_key: "work_life_balance",
    options: [
      option("BOUNDARIES", "Boundaries"),
      option("RECOVERY", "Recovery"),
      option("FOCUS_BLOCKS", "Focus Blocks"),
      option("FLEXIBILITY", "Flexibility"),
    ],
    required: false,
  },
  {
    section_id: "relationships_social",
    title: "Relationships & social",
    type: "chips",
    field_key: "relationships_social",
    options: [
      option("QUALITY_TIME", "Quality Time"),
      option("COMMUNITY", "Community"),
      option("FAMILY", "Family"),
      option("FRIENDS", "Friends"),
    ],
    required: false,
  },
  {
    section_id: "home_environment",
    title: "Home & environment",
    type: "chips",
    field_key: "home_environment",
    options: [
      option("CALM_SPACE", "Calm Space"),
      option("ORGANIZED", "Organized"),
      option("NATURE", "Nature"),
      option("INSPIRING", "Inspiring"),
    ],
    required: false,
  },
  {
    section_id: "personal_priorities",
    title: "Personal priorities",
    type: "chips",
    field_key: "personal_priorities",
    options: [
      option("JOY", "Joy"),
      option("REST", "Rest"),
      option("CONNECTION", "Connection"),
      option("CREATIVITY", "Creativity"),
      option("ADVENTURE", "Adventure"),
      option("HEALTH", "Health"),
      option("BALANCE", "Balance"),
      option("GROWTH", "Growth"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "neglected",
    title: "What feels neglected?",
    type: "chips",
    field_key: "neglected",
    options: [
      option("SELF_CARE", "Self Care"),
      option("RELATIONSHIPS", "Relationships"),
      option("HOBBIES", "Hobbies"),
      option("MOVEMENT", "Movement"),
      option("LEARNING", "Learning"),
      option("REST", "Rest"),
      option("HOME", "Home"),
      option("NUTRITION", "Nutrition"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "future_lifestyle_goals",
    title: "Future lifestyle goals",
    type: "chips",
    field_key: "future_lifestyle_goals",
    options: [
      option("VIBRANT_HEALTH", "Vibrant Health"),
      option("DEEP_CONNECTIONS", "Deeper Connections"),
      option("CREATIVE_LIFE", "Creative Life"),
      option("ADVENTURE_READY", "Adventure Ready"),
      option("BALANCED_RHYTHM", "Balanced Rhythm"),
    ],
    required: true,
    min_selected: 1,
  },
];

export const lifestyleTemplate = personalTemplateBase(
  "lifestyle",
  "LIFESTYLE",
  "Lifestyle Setup",
  "Design the life you want to live day to day.",
  {
    badge_label: "LIFESTYLE",
    title: "Lifestyle Setup",
    body: "Design the life you want to live day to day.",
  },
  lifestyleSections,
  {
    label: "Activate Lifestyle",
    footer_note: "Your lifestyle rhythm adapts as you live",
  },
  {
    title: "Lifestyle Curator",
    badge_label: "Intelligence Profile",
  },
);

const relationshipsSections: SetupSection[] = [
  {
    section_id: "relationship_focus",
    title: "Relationship vision",
    type: "chips",
    field_key: "relationship_focus",
    options: [
      option("PARTNER", "Partner"),
      option("FAMILY", "Family"),
      option("FRIENDS", "Friends"),
      option("COMMUNITY", "Community"),
      option("WORK", "Work"),
      option("SELF", "Self"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "current_state",
    title: "Current relationships",
    type: "single_choice",
    field_key: "current_state",
    options: [
      option("CONNECTED", "Connected"),
      option("DISTANT", "Distant"),
      option("REBUILDING", "Rebuilding"),
      option("OVERWHELMED", "Overwhelmed"),
      option("GROWING", "Growing"),
    ],
    required: true,
  },
  // Core backend keys only — circle fields (family/partner/friends/…) live in the
  // presentation catalog and appear only when the API returns them.
  {
    section_id: "communication_style",
    title: "Communication style",
    type: "chips",
    field_key: "strength_drivers",
    options: [
      option("CONSISTENCY", "Consistency"),
      option("HONESTY", "Honesty"),
      option("EMPATHY", "Empathy"),
      option("SHARED_GOALS", "Shared Goals"),
      option("PRESENCE", "Presence"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "relationship_goals",
    title: "Relationship goals",
    type: "chips",
    field_key: "investment_areas",
    options: [
      option("LISTENING", "Listening"),
      option("PLANNING", "Planning"),
      option("CELEBRATING", "Celebrating"),
      option("REPAIRING", "Repairing"),
      option("BOUNDARIES", "Boundaries"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "want_more",
    title: "What do you want more of?",
    type: "chips",
    field_key: "want_more",
    options: [
      option("QUALITY_TIME", "Quality Time"),
      option("TRUST", "Trust"),
      option("OPENNESS", "Openness"),
      option("SUPPORT", "Support"),
      option("FUN", "Fun"),
    ],
    required: true,
    min_selected: 1,
  },
  {
    section_id: "neglected",
    title: "What feels neglected?",
    type: "chips",
    field_key: "neglected",
    options: [
      option("CHECK_INS", "Check-ins"),
      option("BOUNDARIES", "Boundaries"),
      option("APPRECIATION", "Appreciation"),
      option("SHARED_TIME", "Shared Time"),
      option("EMOTIONAL_SUPPORT", "Emotional Support"),
    ],
    required: true,
    min_selected: 1,
  },
];

export const relationshipsTemplate = personalTemplateBase(
  "relationships",
  "RELATIONSHIPS",
  "Relationships Setup",
  "Build stronger connections with intention.",
  {
    badge_label: "RELATIONSHIPS",
    title: "Relationships Setup",
    body: "Build stronger connections with intention.",
  },
  relationshipsSections,
  {
    label: "Activate Relationships",
    footer_note: "Your connection rhythm adapts as you invest",
  },
  {
    title: "Connection Builder",
    badge_label: "Intelligence Profile",
  },
);

export const MY_MONEY_TEMPLATES = [
  lifeOperationsTemplate,
  futureBuildingTemplate,
  lifestyleTemplate,
  relationshipsTemplate,
];
