"""010 Targeted fixes for source-SQL defects

Revision ID: mom_10_fixes
Revises: mom_09_seed_data
Create Date: generated by docs/screens/_build_fixes.py

Repairs the fixable defects that migrations 001-009 logged into
``mom_migration_skips``. Each statement here corrects a genuine flaw in the
source SQL documents (wrong table/column names, an illegal ``UNIQUE`` over
expressions, a duplicate definition that shadowed the intended one, or columns
that a later view depends on) or simply re-runs a statement that originally
failed only because of ordering.

After applying the fixes, the resolved rows are removed from
``mom_migration_skips``. Five defects remain intentionally logged because they
reference source objects that were never defined anywhere in the documents and
cannot be repaired without a design decision:

  * ``vw_personal_moment_journey``      -> table ``personal_events`` is undefined
  * ``vw_business_journey_v2``          -> table ``business_journey_events`` is undefined
  * ``trg_runway_refresh``              -> table ``business_runway_transactions`` is undefined
  * ``trg_team_operations_refresh``     -> table ``team_operation_activities`` is undefined
  * ``trg_business_operations_refresh`` -> table ``business_operation_records`` is undefined

The downgrade removes every object/column this migration introduced and
restores the original ``fn_validate_driver_weights`` definition.
"""
from __future__ import annotations

import logging
import os

from alembic import op

revision = "mom_10_fixes"
down_revision = "mom_09_seed_data"
branch_labels = None
depends_on = None

_SPLIT = "\n-- >>>STMT<<<\n"
_log = logging.getLogger("alembic.momentra")
_SQL_DIR = os.path.join(os.path.dirname(__file__), "sql")

_RESOLVED = [('mom_04_business', 259), ('mom_05_shared', 1), ('mom_05_shared', 2), ('mom_05_shared', 3), ('mom_06_views', 19), ('mom_06_views', 25), ('mom_06_views', 37), ('mom_06_views', 51), ('mom_06_views', 55), ('mom_06_views', 56), ('mom_06_views', 60), ('mom_06_views', 63), ('mom_06_views', 64), ('mom_06_views', 65), ('mom_06_views', 67), ('mom_06_views', 75), ('mom_06_views', 77), ('mom_06_views', 79), ('mom_06_views', 88), ('mom_06_views', 89), ('mom_06_views', 90), ('mom_06_views', 91), ('mom_07_functions', 271)]


def _statements(fname: str):
    with open(os.path.join(_SQL_DIR, fname), encoding="utf-8") as fh:
        raw = fh.read()
    return [s.strip() for s in raw.split(_SPLIT) if s.strip()]


def _run(fname: str) -> None:
    bind = op.get_bind()
    for stmt in _statements(fname):
        bind.exec_driver_sql(stmt)


def upgrade() -> None:
    _run("mom_10_fixes.up.sql")
    # Clear the rows we just resolved so mom_migration_skips only lists the
    # genuinely-unfixable (undefined-source) defects.
    bind = op.get_bind()
    if _RESOLVED:
        values = ", ".join("('%s', %d)" % (m, s) for (m, s) in _RESOLVED)
        deleted = bind.exec_driver_sql(
            "DELETE FROM mom_migration_skips "
            "WHERE (migration, seq) IN (" + values + ")"
        ).rowcount
        remaining = list(
            bind.exec_driver_sql("SELECT migration, seq FROM mom_migration_skips ORDER BY migration, seq")
        )
        _log.warning(
            "mom_10_fixes: resolved %s defect(s); %s undefined-source defect(s) remain: %s",
            deleted,
            len(remaining),
            ", ".join("%s#%s" % (r[0], r[1]) for r in remaining) or "none",
        )


def downgrade() -> None:
    _run("mom_10_fixes.down.sql")
