import { buildBundle, field, groupTripEndpoint, type ActionDef } from "../builders";
import type { QuickAddTemplateBundle } from "../types";

const TEMPLATE_ID = "group.trip";
const CONTEXT = "SHARED_EXPERIENCE" as const;
const MODULES = ["pulse", "live", "memory", "operations_hub"];

function tripAction(
  def: Omit<ActionDef, "backend_endpoint" | "output_event" | "affects_modules"> & {
    contextPath: string;
    createPost: string;
    eventType: string;
    refTable?: string;
  },
): ActionDef {
  return {
    ...def,
    backend_endpoint: groupTripEndpoint(def.contextPath, def.createPost),
    output_event: {
      event_type: def.eventType,
      ref_table: def.refTable,
    },
    affects_modules: MODULES,
  };
}

const actions: ActionDef[] = [
  tripAction({
    action_id: "PARTICIPANT",
    reusable_type: "participant",
    label: "Participant",
    icon: "person_add",
    section: "People",
    display_order: 1,
    cta_label: "Add Participant",
    fields: [
      field("full_name", "Full name", "text", { required: true }),
      field("phone", "Phone", "text"),
      field("email", "Email", "text"),
      field("relationship_type", "Relationship", "single_select", { required: true }),
      field("assigned_role", "Role", "text"),
      field("status", "Status", "single_select"),
    ],
    validation: { required_fields: ["full_name", "relationship_type"] },
    impact_preview: { modules: MODULES, summary_template: "Invites {full_name} as participant" },
    contextPath: "participant",
    createPost: "POST /api/v1/group/trips/{moment_id}/guests",
    eventType: "PARTICIPANT_CREATED",
    refTable: "moment_store.runtime.guests",
  }),
  tripAction({
    action_id: "PLANNING_ITEM",
    reusable_type: "task",
    label: "Planning Item",
    icon: "task_alt",
    section: "Planning",
    display_order: 2,
    cta_label: "Add Planning Item",
    fields: [
      field("title", "Title", "text", { required: true }),
      field("planning_category", "Category", "single_select"),
      field("due_date", "Due date", "date"),
      field("planning_status", "Status", "single_select"),
    ],
    validation: { required_fields: ["title"] },
    impact_preview: { modules: MODULES, summary_template: "Adds planning item {title}" },
    contextPath: "planning-item",
    createPost: "POST /api/v1/group/trips/{moment_id}/plans",
    eventType: "PLANNING_ITEM_CREATED",
  }),
  tripAction({
    action_id: "BOOKING",
    reusable_type: "booking",
    label: "Booking",
    icon: "flight_takeoff",
    section: "Planning",
    display_order: 3,
    cta_label: "Add Booking",
    fields: [
      field("booking_type", "Booking type", "single_select", { required: true }),
      field("provider", "Provider", "text"),
      field("booking_status", "Status", "single_select"),
      field("amount_minor", "Cost", "amount"),
      field("description", "Notes", "textarea"),
    ],
    validation: { required_fields: ["booking_type"] },
    impact_preview: { modules: MODULES, summary_template: "Adds {booking_type} booking" },
    contextPath: "booking",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/booking",
    eventType: "BOOKING_CREATED",
  }),
  tripAction({
    action_id: "EXPENSE",
    reusable_type: "expense",
    label: "Expense",
    icon: "payments",
    section: "Money",
    display_order: 4,
    cta_label: "Record Expense",
    fields: [
      field("amount_minor", "Amount", "amount", { required: true }),
      field("category", "Category", "single_select", { required: true }),
      field("split_type", "Split type", "segmented"),
      field("paid_by_user_id", "Paid by", "member_picker"),
      field("description", "Description", "textarea"),
    ],
    validation: { required_fields: ["amount_minor", "category"] },
    impact_preview: { modules: MODULES, summary_template: "Records trip expense in {category}" },
    contextPath: "expense",
    createPost: "POST /api/v1/group/trips/{moment_id}/expenses",
    eventType: "GROUP_EXPENSE_CREATED",
    refTable: "moment_store.runtime.expenses",
  }),
  tripAction({
    action_id: "CONTRIBUTION",
    reusable_type: "contribution",
    label: "Contribution",
    icon: "savings",
    section: "Money",
    display_order: 5,
    cta_label: "Record Contribution",
    fields: [
      field("amount_minor", "Amount", "amount", { required: true }),
      field("contributor_id", "Contributor", "member_picker"),
      field("payment_method", "Payment method", "single_select"),
    ],
    validation: { required_fields: ["amount_minor"] },
    impact_preview: { modules: MODULES, summary_template: "Records contribution of ₹{amount_minor}" },
    contextPath: "contribution",
    createPost: "POST /api/v1/group/trips/{moment_id}/contributions",
    eventType: "CONTRIBUTION_CREATED",
  }),
  tripAction({
    action_id: "BUDGET",
    reusable_type: "contribution",
    label: "Budget",
    icon: "account_balance_wallet",
    section: "Money",
    display_order: 5,
    cta_label: "Set Budget",
    fields: [
      field("total_amount_major", "Total budget", "amount", { required: true }),
      field("template_id", "Template", "segmented"),
      field("split_method", "Split method", "segmented"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["total_amount_major"] },
    impact_preview: { modules: MODULES, summary_template: "Saves planning budget of ₹{total_amount_major}" },
    contextPath: "budget",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/budget/plans",
    eventType: "BUDGET_PLAN_CREATED",
  }),
  tripAction({
    action_id: "VENDOR",
    reusable_type: "participant",
    label: "Vendor",
    icon: "handshake",
    section: "Support",
    display_order: 6,
    cta_label: "Add Vendor",
    fields: [
      field("vendor_name", "Vendor name", "text", { required: true }),
      field("vendor_type", "Vendor type", "single_select"),
      field("contact", "Contact", "text"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["vendor_name"] },
    impact_preview: { modules: MODULES, summary_template: "Adds vendor {vendor_name}" },
    contextPath: "vendor",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/vendor",
    eventType: "VENDOR_CREATED",
  }),
  tripAction({
    action_id: "ATTENDANCE",
    reusable_type: "participant",
    label: "Attendance",
    icon: "checklist",
    section: "Support",
    display_order: 7,
    cta_label: "Log Attendance",
    fields: [
      field("member_id", "Member", "member_picker", { required: true }),
      field("attendance_type", "Attendance type", "single_select", { required: true }),
      field("status", "Status", "single_select"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["member_id", "attendance_type"] },
    impact_preview: { modules: MODULES, summary_template: "Updates attendance for member" },
    contextPath: "attendance",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/attendance",
    eventType: "ATTENDANCE_LOGGED",
  }),
  tripAction({
    action_id: "UPDATE",
    reusable_type: "update",
    label: "Update",
    icon: "campaign",
    section: "Support",
    display_order: 8,
    cta_label: "Post Update",
    fields: [
      field("update_type", "Update type", "single_select"),
      field("title", "Title", "text", { required: true }),
      field("body", "Message", "textarea", { required: true }),
      field("visibility", "Visibility", "single_select"),
    ],
    validation: { required_fields: ["title", "body"] },
    impact_preview: { modules: MODULES, summary_template: "Posts update: {title}" },
    contextPath: "update",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/update",
    eventType: "TRIP_UPDATE_POSTED",
  }),
  tripAction({
    action_id: "MEMORY",
    reusable_type: "memory",
    label: "Memory",
    icon: "photo_library",
    section: "Memory & Decisions",
    display_order: 9,
    cta_label: "Capture Memory",
    fields: [
      field("memory_category", "Category", "single_select"),
      field("memory_format", "Format", "single_select"),
      field("media", "Media", "media_upload", { required: true }),
      field("caption", "Caption", "textarea"),
    ],
    validation: { required_fields: ["media"] },
    impact_preview: { modules: MODULES, summary_template: "Captures trip memory" },
    contextPath: "memory",
    createPost: "POST /api/v1/group/trips/{moment_id}/memories",
    eventType: "MEMORY_CAPTURED",
  }),
  tripAction({
    action_id: "POLL",
    reusable_type: "decision",
    label: "Poll",
    icon: "how_to_vote",
    section: "Memory & Decisions",
    display_order: 10,
    cta_label: "Create Poll",
    fields: [
      field("question", "Question", "text", { required: true }),
      field("options", "Options", "multi_select", { required: true }),
      field("allow_multiple_answers", "Allow multiple answers", "toggle"),
    ],
    validation: { required_fields: ["question", "options"], custom_rule: "poll_min_options_2" },
    impact_preview: { modules: MODULES, summary_template: "Creates poll: {question}" },
    contextPath: "poll",
    createPost: "POST /api/v1/group/trips/{moment_id}/quick-add/poll",
    eventType: "POLL_CREATED",
  }),
];

export const GROUP_TRIP_QUICK_ADD: QuickAddTemplateBundle = buildBundle(
  TEMPLATE_ID,
  CONTEXT,
  "sectioned_hub",
  actions,
  { default_action_id: "PARTICIPANT" },
);
