import { buildBundle, field, groupLivingEndpoint, type ActionDef } from "../builders";
import type { QuickAddTemplateBundle } from "../types";

const TEMPLATE_ID = "group.living";
const CONTEXT = "SHARED_LIVING" as const;
const MODULES = ["pulse", "live", "memory", "operations_hub"];

function livingAction(
  def: Omit<ActionDef, "backend_endpoint" | "output_event" | "affects_modules"> & {
    endpointKey: string;
    eventType: string;
    refTable?: string;
  },
): ActionDef {
  return {
    ...def,
    backend_endpoint: groupLivingEndpoint(def.endpointKey),
    output_event: { event_type: def.eventType, ref_table: def.refTable },
    affects_modules: MODULES,
  };
}

const actions: ActionDef[] = [
  livingAction({
    action_id: "RESIDENT",
    reusable_type: "participant",
    label: "Resident",
    icon: "person_add",
    section: "People",
    display_order: 1,
    cta_label: "Add Resident",
    fields: [
      field("full_name", "Full name", "text", { required: true }),
      field("resident_role", "Role", "single_select"),
      field("relationship_type", "Relationship", "single_select"),
      field("status", "Status", "single_select"),
    ],
    validation: { required_fields: ["full_name"] },
    impact_preview: { modules: MODULES, summary_template: "Adds resident {full_name}" },
    endpointKey: "residents",
    eventType: "RESIDENT_ADDED",
    refTable: "moment_store.runtime.residents",
  }),
  livingAction({
    action_id: "EXPENSE",
    reusable_type: "expense",
    label: "Expense",
    icon: "payments",
    section: "Money",
    display_order: 2,
    cta_label: "Add Expense",
    fields: [
      field("amount_minor", "Amount", "amount", { required: true }),
      field("expense_category", "Category", "single_select", { required: true }),
      field("split_type", "Split type", "segmented"),
      field("expense_date", "Date", "date"),
    ],
    validation: { required_fields: ["amount_minor", "expense_category"] },
    impact_preview: { modules: MODULES, summary_template: "Records home expense in {expense_category}" },
    endpointKey: "expenses",
    eventType: "LIVING_EXPENSE_RECORDED",
    refTable: "moment_store.runtime.expenses",
  }),
  livingAction({
    action_id: "CONTRIBUTION",
    reusable_type: "contribution",
    label: "Contribution",
    icon: "savings",
    section: "Money",
    display_order: 3,
    cta_label: "Record Contribution",
    fields: [
      field("amount_minor", "Amount", "amount", { required: true }),
      field("contribution_category", "Category", "single_select"),
      field("payment_method", "Payment method", "single_select"),
      field("status", "Status", "single_select"),
    ],
    validation: { required_fields: ["amount_minor"] },
    impact_preview: { modules: MODULES, summary_template: "Records contribution" },
    endpointKey: "contributions",
    eventType: "CONTRIBUTION_RECORDED",
  }),
  livingAction({
    action_id: "TASK",
    reusable_type: "task",
    label: "Task",
    icon: "checklist",
    section: "Responsibilities",
    display_order: 4,
    cta_label: "Add Task",
    fields: [
      field("title", "Task", "text", { required: true }),
      field("task_category", "Category", "single_select"),
      field("frequency", "Frequency", "single_select"),
      field("priority", "Priority", "segmented"),
      field("assignee_id", "Assignee", "member_picker"),
    ],
    validation: { required_fields: ["title"] },
    impact_preview: { modules: MODULES, summary_template: "Adds task {title}" },
    endpointKey: "tasks",
    eventType: "TASK_CREATED",
  }),
  livingAction({
    action_id: "ASSET",
    reusable_type: "update",
    label: "Asset",
    icon: "inventory_2",
    section: "Home",
    display_order: 5,
    cta_label: "Add Asset",
    fields: [
      field("asset_type", "Asset type", "single_select"),
      field("name", "Name", "text", { required: true }),
      field("condition", "Condition", "single_select"),
      field("location", "Location", "text"),
    ],
    validation: { required_fields: ["name"] },
    impact_preview: { modules: MODULES, summary_template: "Registers asset {name}" },
    endpointKey: "assets",
    eventType: "ASSET_REGISTERED",
  }),
  livingAction({
    action_id: "RULE",
    reusable_type: "update",
    label: "Rule",
    icon: "gavel",
    section: "Responsibilities",
    display_order: 6,
    cta_label: "Add Rule",
    fields: [
      field("rule_type", "Rule type", "single_select"),
      field("text", "Rule text", "textarea", { required: true }),
      field("visibility", "Visibility", "single_select"),
    ],
    validation: { required_fields: ["text"] },
    impact_preview: { modules: MODULES, summary_template: "Adds house rule" },
    endpointKey: "rules",
    eventType: "RULE_ADDED",
  }),
  livingAction({
    action_id: "MAINTENANCE",
    reusable_type: "task",
    label: "Maintenance",
    icon: "build",
    section: "Home",
    display_order: 7,
    cta_label: "Log Maintenance",
    fields: [
      field("maintenance_type", "Type", "single_select", { required: true }),
      field("severity", "Severity", "segmented"),
      field("description", "Description", "textarea", { required: true }),
      field("due_date", "Due date", "date"),
    ],
    validation: { required_fields: ["maintenance_type", "description"] },
    impact_preview: { modules: MODULES, summary_template: "Logs maintenance issue" },
    endpointKey: "maintenance",
    eventType: "MAINTENANCE_LOGGED",
  }),
  livingAction({
    action_id: "UPDATE",
    reusable_type: "update",
    label: "Update",
    icon: "campaign",
    section: "Social & Moments",
    display_order: 8,
    cta_label: "Post Update",
    fields: [
      field("update_type", "Update type", "single_select"),
      field("visibility", "Visibility", "single_select"),
      field("body", "Announcement", "textarea", { required: true }),
    ],
    validation: { required_fields: ["body"] },
    impact_preview: { modules: MODULES, summary_template: "Posts house update" },
    endpointKey: "updates",
    eventType: "LIVING_UPDATE_POSTED",
  }),
  livingAction({
    action_id: "POLL",
    reusable_type: "decision",
    label: "Poll",
    icon: "how_to_vote",
    section: "Social & Moments",
    display_order: 9,
    cta_label: "Create Poll",
    fields: [
      field("question", "Question", "text", { required: true }),
      field("options", "Options", "multi_select", { required: true }),
      field("allow_multiple_answers", "Allow multiple answers", "toggle"),
    ],
    validation: { required_fields: ["question", "options"] },
    impact_preview: { modules: MODULES, summary_template: "Creates house poll" },
    endpointKey: "polls",
    eventType: "LIVING_POLL_CREATED",
  }),
  livingAction({
    action_id: "MEMORY",
    reusable_type: "memory",
    label: "Memory",
    icon: "photo_library",
    section: "Social & Moments",
    display_order: 10,
    cta_label: "Capture Memory",
    fields: [
      field("memory_category", "Category", "single_select"),
      field("memory_format", "Format", "single_select"),
      field("media", "Media", "media_upload"),
      field("caption", "Caption", "textarea"),
    ],
    validation: { required_fields: ["memory_category"] },
    impact_preview: { modules: MODULES, summary_template: "Captures shared memory" },
    endpointKey: "memories",
    eventType: "LIVING_MEMORY_CAPTURED",
  }),
];

export const GROUP_LIVING_QUICK_ADD: QuickAddTemplateBundle = buildBundle(
  TEMPLATE_ID,
  CONTEXT,
  "sectioned_hub",
  actions,
  { default_action_id: "RESIDENT" },
);
