import { buildBundle, field, personalEndpoint, type ActionDef } from "../builders";
import type { QuickAddTemplateBundle } from "../types";

const TEMPLATE_ID = "personal.lifestyle";
const CONTEXT = "LIFESTYLE" as const;
const MODULES = ["pulse", "live", "memory", "moments"];

const actions: ActionDef[] = [
  {
    action_id: "LIFESTYLE_EXPENSE",
    reusable_type: "expense",
    label: "Expense",
    icon: "payments",
    display_order: 1,
    cta_label: "Save Expense",
    fields: [
      field("amount", "Amount", "amount", { required: true }),
      field("spend_category", "Category", "chip_grid"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["amount"] },
    impact_preview: { modules: MODULES, summary_template: "Records lifestyle expense ₹{amount}" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "LIFESTYLE_EXPENSE", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
  {
    action_id: "EXPERIENCE",
    reusable_type: "memory",
    label: "Experience",
    icon: "explore",
    display_order: 2,
    cta_label: "Save Experience",
    fields: [
      field("experience_type", "Experience type", "single_select", { required: true }),
      field("experience_quality", "How was it?", "chip_grid"),
      field("energy_impact", "How did it affect your energy?", "chip_grid"),
      field("people_context", "Who were you with? — optional", "chip_grid"),
      field("location_context", "Where was it? — optional", "chip_grid"),
      field("value_received", "What did you get from it?", "chip_grid"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["experience_type"] },
    impact_preview: { modules: MODULES, summary_template: "Logs {experience_type} experience" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "EXPERIENCE", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
  {
    action_id: "WELLBEING",
    reusable_type: "mood",
    label: "Wellbeing",
    icon: "spa",
    display_order: 3,
    cta_label: "Log Wellbeing",
    fields: [
      field("wellbeing_areas", "Wellbeing areas", "chip_grid", { required: true }),
      field("wellbeing_state", "State", "single_select", { required: true }),
      field("contributors", "Contributors", "multi_select"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["wellbeing_state", "wellbeing_areas"] },
    impact_preview: { modules: MODULES, summary_template: "Logs wellbeing state {wellbeing_state}" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "WELLBEING", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
  {
    action_id: "DISCOVERY",
    reusable_type: "update",
    label: "Discover",
    icon: "travel_explore",
    display_order: 4,
    cta_label: "Save Discovery",
    fields: [
      field("discovery_type", "Discovery type", "single_select", { required: true }),
      field("discovery_impact", "Impact", "chip_grid"),
      field("curiosity_level", "Curiosity", "chip_grid"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["discovery_type"] },
    impact_preview: { modules: MODULES, summary_template: "Saves discovery: {discovery_type}" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "DISCOVERY", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
  {
    action_id: "EXPRESSION",
    reusable_type: "update",
    label: "Create",
    icon: "brush",
    display_order: 5,
    cta_label: "Save Creation",
    fields: [
      field("creation_type", "Creation type", "single_select", { required: true }),
      field("satisfaction_level", "How satisfied are you with it?", "chip_grid"),
      field("time_invested", "Time invested", "chip_grid"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["creation_type"] },
    impact_preview: { modules: MODULES, summary_template: "Logs creation: {creation_type}" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "EXPRESSION", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
  {
    action_id: "ADJUST",
    reusable_type: "update",
    label: "Adjust",
    icon: "tune",
    display_order: 6,
    cta_label: "Update Lifestyle",
    fields: [
      field("adjustment_area", "What area do you want to adjust?", "single_select", { required: true }),
      field("priority_level", "How important is this change?", "chip_grid"),
      field("confidence_level", "How confident are you?", "chip_grid"),
      field("notes", "Notes", "textarea"),
    ],
    validation: { required_fields: ["adjustment_area"] },
    impact_preview: { modules: MODULES, summary_template: "Adjusts {adjustment_area}" },
    backend_endpoint: personalEndpoint("POST /api/v1/personal/live/quick-add"),
    output_event: { event_type: "ADJUST", ref_table: "personal_quick_add_events" },
    affects_modules: MODULES,
  },
];

export const LIFESTYLE_QUICK_ADD: QuickAddTemplateBundle = buildBundle(
  TEMPLATE_ID,
  CONTEXT,
  "tabbed_hub",
  actions,
  { default_action_id: "LIFESTYLE_EXPENSE" },
);
