/** Centralized API path constants — all clients should reference these. */
export const API_ENDPOINTS = {
  auth: {
    firebaseExchange: "api/v1/auth/firebase/exchange",
    sync: "api/v1/auth/sync",
    exchange: "api/v1/auth/exchange",
    refresh: "api/v1/auth/refresh",
    logout: "api/v1/auth/logout",
    logoutAll: "api/v1/auth/logout-all",
  },
  me: "api/v1/me",
  app: {
    bootstrap: "api/v1/app/bootstrap",
    preferences: "api/v1/app/preferences",
  },
  moments: {
    list: "api/v1/moments",
    home: "api/v1/moments/home",
    byId: (id: string) => `api/v1/moments/${id}`,
    activate: (id: string) => `api/v1/moments/${id}/activate`,
    complete: (id: string) => `api/v1/moments/${id}/complete`,
    archive: (id: string) => `api/v1/moments/${id}/archive`,
  },
  home: {
    myMoney: "api/v1/my-money/home",
    group: "api/v1/group/home",
    business: "api/v1/business/home",
    circle: "api/v1/circle/home",
    life360: "api/v1/life360/home",
    memory: "api/v1/memory/home",
  },
  circle: {
    home: "api/v1/circle/home",
    refresh: "api/v1/circle/refresh",
    read: "api/v1/circle/read",
    analytics: "api/v1/circle/analytics",
    summary: "api/v1/circle/summary",
  },
  life360: {
    home: "api/v1/life360/home",
    refresh: "api/v1/life360/refresh",
    read: "api/v1/life360/read",
    analytics: "api/v1/life360/analytics",
    summary: "api/v1/life360/summary",
  },
  personal: {
    sessionBootstrap: "api/v1/personal/session/bootstrap",
    pulse: "api/v1/personal/pulse",
    momentsHome: "api/v1/personal/moments/home",
    memory: "api/v1/personal/memory",
    life: "api/v1/personal/life",
    createOptions: "api/v1/personal/create/options",
    moments: "api/v1/personal/moments",
    setup: (momentId: string) => `api/v1/personal/moments/${momentId}/setup`,
    setupDraft: (momentId: string) => `api/v1/personal/moments/${momentId}/setup/draft`,
    setupPreview: (momentId: string) => `api/v1/personal/moments/${momentId}/setup/preview`,
  },
  group: {
    sessionBootstrap: "api/v1/group/session/bootstrap",
    home: "api/v1/group/home",
    pulse: "api/v1/group/pulse",
    momentsHome: "api/v1/group/moments/home",
    memory: "api/v1/group/memory",
    createOptions: "api/v1/group/create/options",
  },
  business: {
    sessionBootstrap: "api/v1/business/session/bootstrap",
    home: "api/v1/business/home",
    createOptions: "api/v1/business/create/options",
  },
} as const;
